USE [PersonalTrainer]
GO

/****** Object:  Table [dbo].[Workout_Plan]    Script Date: 2022/02/22 19:07:17 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Workout_Plan](
	[Client_ID] [int] NOT NULL,
	[Workout_ID] [int] NOT NULL,
 CONSTRAINT [PK_Workout_Plan] PRIMARY KEY CLUSTERED 
(
	[Client_ID] ASC,
	[Workout_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


